// Generated by CoffeeScript 1.4.0
(function() {
  var apto_util, assert, fs, listfilesSync, map, test, watch;

  fs = require("fs");

  assert = require("assert");

  map = Array.prototype.map;

  apto_util = require("../lib/util");

  listfilesSync = apto_util.listfilesSync;

  watch = apto_util.watch;

  test = function(desc, fn) {
    return fn();
  };

  test("listfilesSync", function() {
    listfilesSync("test");
    listfilesSync("test/test_project");
    map.call(listfilesSync("."), function(filename) {
      return assert.ok(fs.statSync(filename).isFile());
    });
    return map.call(listfilesSync(".", {
      recur: true
    }), function(filename) {
      return assert.ok(fs.statSync(filename).isFile());
    });
  });

  test("watch", function() {
    assert.throws(function() {
      return watch("not array", function(filename) {
        return println(filename);
      });
    }, Error);
    return watch(["./test", "."], function(filename) {
      return println("changed " + filename);
    });
  });

}).call(this);
