// Generated by CoffeeScript 1.4.0
(function() {
  var apto, express, main, path, site, swig;

  path = require("path");

  swig = require("swig");

  express = require('express');

  apto = require("../apto");

  swig.init({
    cache: false,
    root: "."
  });

  site = apto.Site.create({
    build_path: "build",
    static_path: "static",
    routes: {
      "(.*)+/?": "page"
    },
    page: function(file, name) {
      var pages;
      pages = apto.util.listfilesSync("page", {
        recur: true
      });
      return file.write(swig.compileFile(path.join("page/", name)).render({
        pages: pages
      }));
    },
    buildall: function() {
      var pages;
      pages = apto.util.listfilesSync("page", {
        recur: true
      });
      site.build(pages);
      return site.build_static();
    }
  });

  main = function() {
    var command, option1, port;
    command = process.argv[2];
    option1 = process.argv[3];
    switch (command) {
      case "build":
        return site.buildall();
      case "serve":
        port = option1 || 8000;
        console.log("development server started at localhost: " + port);
        site.buildall();
        apto.util.watch(["page", "static", "layout"], function(filename) {
          return site.buildall();
        });
        return express().use(express["static"](site.build_path)).listen(port);
      default:
        return console.log("\n  Commands:\n\n    serve  <port>   Start an development server, auto reloads changes for you.\n    build           Build site.\n\n");
    }
  };

  main();

}).call(this);
